import type { ChatbotContext, RenderedSection } from "@/lib/types";

/**
 * The ONLY shape of a published idea that public/visitor-facing code is allowed
 * to see. This is a deny-by-default allowlist: every field here is explicitly
 * chosen and public-safe. Internal evaluation data (triage verdicts/scores,
 * kill assumptions, development internals, raw research, outcomes, raw_input,
 * journal, refinements) is excluded by *omission* — it is never carried onto
 * this type, so a future internal field cannot leak unless someone deliberately
 * adds it here AND to `toPublicIdea`.
 *
 * Do not widen this type to `Idea` or spread a raw `ideas` row into it.
 */
export interface PublicIdea {
  /** Public slug for the portfolio page. */
  slug: string;
  /** Distilled, public-facing headline. */
  headline: string;
  /** Light public metadata. */
  domain: string | null;
  state: string | null;
  created_at: string;
  /**
   * The distilled public character that seeds the public agent. Generated by
   * the distiller under a content contract that forbids internal language;
   * see distill.py pass 3. This is the only generated field on the allow side.
   */
  chatbotContext: ChatbotContext;
  /**
   * The rendered portfolio sections — exactly what a visitor already sees on
   * the public project page. Safe to give the agent as reference material.
   */
  publicSummary: { sections: RenderedSection[] };
}

/**
 * Minimal shapes this projection reads from. Intentionally narrow so callers
 * cannot accidentally pass internal blobs through.
 */
interface PublishedRowLike {
  domain?: string | null;
  state?: string | null;
  created_at?: string | null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  portfolio?: { headline?: string | null; slug?: string | null } & Record<string, any>;
}

interface ActiveVersionLike {
  chatbot_context: ChatbotContext;
  public_summary: { sections: RenderedSection[] };
}

/**
 * Build the public-safe projection of a published idea. Constructs the result
 * field-by-field from explicitly named sources — it never spreads `row` and
 * never reads triage / development / outcomes / raw_input / journal /
 * refinements. Deny-by-default.
 */
export function toPublicIdea(
  row: PublishedRowLike,
  activeVersion: ActiveVersionLike,
): PublicIdea {
  return {
    slug: row.portfolio?.slug ?? "",
    headline: row.portfolio?.headline ?? "",
    domain: row.domain ?? null,
    state: row.state ?? null,
    created_at: row.created_at ? String(row.created_at).slice(0, 10) : "unknown",
    chatbotContext: activeVersion.chatbot_context,
    publicSummary: activeVersion.public_summary ?? { sections: [] },
  };
}
